// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtWSNOJhrs0Wko1oP8zn-A8RoTf9xqR-E',
    appId: '1:1023759846976:web:671d82cb6471cdefab19a5',
    messagingSenderId: '1023759846976',
    projectId: 'smart-nursery-7a6f6',
    authDomain: 'smart-nursery-7a6f6.firebaseapp.com',
    storageBucket: 'smart-nursery-7a6f6.firebasestorage.app',
    measurementId: 'G-6V6PR1K2F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmFb9-PJgOKLxGOVwL1VSGodnibqQYY04',
    appId: '1:1023759846976:android:e52eeb49ba832dceab19a5',
    messagingSenderId: '1023759846976',
    projectId: 'smart-nursery-7a6f6',
    storageBucket: 'smart-nursery-7a6f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6B0NNIeHuitxDr6NogsVHJpjNNiC7UyY',
    appId: '1:1023759846976:ios:09d074aad1b2a4a4ab19a5',
    messagingSenderId: '1023759846976',
    projectId: 'smart-nursery-7a6f6',
    storageBucket: 'smart-nursery-7a6f6.firebasestorage.app',
    iosBundleId: 'com.example.smartnursery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6B0NNIeHuitxDr6NogsVHJpjNNiC7UyY',
    appId: '1:1023759846976:ios:09d074aad1b2a4a4ab19a5',
    messagingSenderId: '1023759846976',
    projectId: 'smart-nursery-7a6f6',
    storageBucket: 'smart-nursery-7a6f6.firebasestorage.app',
    iosBundleId: 'com.example.smartnursery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtWSNOJhrs0Wko1oP8zn-A8RoTf9xqR-E',
    appId: '1:1023759846976:web:d208ac81b102f296ab19a5',
    messagingSenderId: '1023759846976',
    projectId: 'smart-nursery-7a6f6',
    authDomain: 'smart-nursery-7a6f6.firebaseapp.com',
    storageBucket: 'smart-nursery-7a6f6.firebasestorage.app',
    measurementId: 'G-5PL2LEMM3L',
  );
}
